---
# Configure a new user environment for the user running the playbook.
- hosts:
    127.0.0.1
    connection: local
  become: no
  tasks:
- name: Get user name
  local_action: command id -nu
  register: id_user
- name: Get group name
  local_action: command id -gn
  register: id_group
- name: Set user and group variables
  set_fact:
    this_user: "{{ id_user.stdout }}"
    this_group: "{{ id_group.stdout }}"
- debug: var=this_user
- debug: var=this_group
- name: Copy bash prompt file
  ansible.builtin.copy:
    src: files/dot.bash_prompt
    dest: "/home/{{ this_user }}/.bash_prompt"
    owner: "{{ this_user }}"
    group: "{{ this_user }}"
    mode: '0664'

- name: Copy bash alias file
  ansible.builtin.copy:
    src: files/dot.bash_alias
    dest: "/home/{{ this_user }}/.bash_alias"
    owner: "{{ this_user }}"
    group: "{{ this_user }}"
    mode: '0664'

- name: Copy tmux configuration file
  ansible.builtin.copy:
    src: files/dot.tmux.conf
    dest: "/home/{{ this_user }}/.tmux.conf"
    owner: "{{ this_user }}"
    group: "{{ this_user }}"
    mode: '0664'

- name: Copy gitconfig
  ansible.builtin.copy:
    src: files/dot.gitconfig
    dest: "/home/{{ this_user }}/.gitconfig"
    owner: "{{ this_user }}"
    group: "{{ this_user }}"
    mode: '0664'

- name: Copy clang-format
  ansible.builtin.copy:
    src: files/dot.clang-format
    dest: "/home/{{ this_user }}/.clang-format"
    owner: "{{ this_user }}"
    group: "{{ this_user }}"
    mode: '0664'

- name: Copy Vim configuration file
  ansible.builtin.copy:
    src: files/dot.vimrc
    dest: "/home/{{ this_user }}/.vimrc"
    owner: "{{ this_user }}"
    group: "{{ this_user }}"
    mode: '0664'

- name: Create User's Vim Colors directory
  ansible.builtin.file:
    path: "/home/{{ this_user }}/.vim/colors"
    state: directory
    mode: '0775'

- name: Copy Vim color scheme file
  ansible.builtin.copy:
    src: files/dot.vim-colors-yk.vim
    dest: "/home/{{ this_user }}/.vim/colors/yk.vim"
    owner: "{{ this_user }}"
    group: "{{ this_user }}"
    mode: '0664'

- name: Create "{{ this_user }}"'s local
  ansible.builtin.file:
    path: "/home/{{ this_user }}/.local"
    state: directory
    owner: "{{ this_user }}"
    group: "{{ this_user }}"
    mode: '0775'

- name: Create "{{ this_user }}"'s TMPDIR
  ansible.builtin.file:
    path: "/home/{{ this_user }}/.local/tmp"
    state: directory
    owner: "{{ this_user }}"
    group: "{{ this_user }}"
    mode: '0775'

- name: Add TMPDIR to bashrc
  ansible.builtin.lineinfile:
    path: "/home/{{ this_user }}/.bashrc"
    state: present
    line: export TMPDIR=~/.local/tmp

- name: Source alias file in bashrc
  ansible.builtin.lineinfile:
    path: "/home/{{ this_user }}/.bashrc"
    state: present
    line: source ~/.bash_alias

- name: Source prompt in bashrc
  ansible.builtin.lineinfile:
    path: "/home/{{ this_user }}/.bashrc"
    state: present
    insertafter: EOF
    line: source ~/.bash_prompt
