---
# Install Packages on RHEL / CentOS
- hosts:
    localhost:
      vars:
        ansible_connection: local
        ansible_python_interpreter: "{{ansible_playbook_python}}"
  become: yes
  tasks:
  - name: Update Packages
    ansible.builtin.dnf:
      name: '*'
      state: latest
  - name: Install EPEL Release
    ansible.builtin.dnf:
      name:
        - epel-release
      state: latest
  - name: Install command line tools
    ansible.builtin.dnf:
      name:
        - clang-tools-extra
        - cmake
        - git
        - htop
        - minicom
        - nmap
        - rsync
        - sed
        - tmux
        - vim
        - xxd
      state: latest
  - name: Install graphical tools
    ansible.builtin.dnf:
      name:
        - gnome-tweaks
        - setools-gui
        - vim-X11
      state: latest
  - name: Remove packages
    ansible.builtin.dnf:
      name:
        - nano
      state: absent
