# Use screen(1) command key
set -g prefix C-a
bind C-a send-prefix
unbind C-b

# 256 Color terminal
set -g default-terminal "screen-256color"
# Put host/date/time in right status
set-option -g status-right "\"#H\" %Y-%m-%d %H:%M"

